apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-postgres-db-pvc
spec:
  storageClassName: booking-localstorage
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: booking-postgres-db-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: booking-localstorage
  hostPath:
    path: "/data/postgres"
    type: DirectoryOrCreate
